apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-url: <base64-encoded-postgres-url>
  postgres-username: <base64-encoded-username>
  postgres-password: <base64-encoded-password>