apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  dbname: cG9zdGdyZXM=  # postgres
  username: cG9zdGdyZXM=  # postgres
  password: bXlzZWNyZXRwYXNzd29yZA==  # mysecretpassword 