apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvcG9zdGdyZXM=  # postgres://postgres-service:5432/postgres
  database-user: cG9zdGdyZXM=  # postgres
  database-password: bXlzZWNyZXRwYXNzd29yZA==  # mysecretpassword 