name: Build and Push Docker Image

on:
  push:
    paths:
      - 'backend/app/**'
      - '.github/workflows/main.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend/app
          file: backend/app/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/course-k8s-top-down:latest